export const DETAIL_HORIZONTAL_MARGIN = 15;

export const BOTTOM_NAV_BAR_HEIGHT = 60;

export const INSTRUCTION_FORM_STARTING_HEIGHT = 34;

export const INGREDIENT_HEIGHT = 35;

export const RECIPE_SUMMARY_WIDTH = 460;